

steps:
  - name: ''
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t  \
          -f Dockerfile --platform=linux/amd64 \
          --build-arg PORT=$$PORT \
          --build-arg DATABASE_URL=$$DATABASE_URL \
          --build-arg JWT_TOKEN=$$JWT_TOKEN \
          --build-arg NODE_ENV=$$NODE_ENV \
          --build-arg SECRET_KEY_ONE=$$SECRET_KEY_ONE \
          --build-arg SECRET_KEY_TWO=$$SECRET_KEY_TWO \
          --build-arg CLIENT_URL=$$CLIENT_URL \
          --build-arg REDIS_HOST=$$REDIS_HOST \
          --build-arg CLOUD_NAME=$$CLOUD_NAME \
          --build-arg CLOUD_API_KEY=$$CLOUD_API_KEY \
          --build-arg CLOUD_API_SECRET=$$CLOUD_API_SECRET \
          --build-arg SENDER_EMAIL=$$SENDER_EMAIL \
          --build-arg SENDER_EMAIL_PASSWORD=$$SENDER_EMAIL_PASSWORD \
          --build-arg SENDGRID_API_KEY=$$SENDGRID_API_KEY \
          --build-arg SENDGRID_SENDER=$$SENDGRID_SENDER .
    secretEnv: ['PORT', 'DATABASE_URL', 'JWT_TOKEN', 'NODE_ENV', 'SECRET_KEY_ONE', 'SECRET_KEY_TWO', 'CLIENT_URL', 'REDIS_HOST', 'CLOUD_NAME', 'CLOUD_API_KEY', 'CLOUD_API_SECRET', 'SENDER_EMAIL', 'SENDER_EMAIL_PASSWORD', 'SENDGRID_API_KEY', 'SENDGRID_SENDER']

  - name: ''
    args:
      [
        'push',
        '',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/784430514655/secrets/PORT/versions/1
      env: 'PORT'
    - versionName: projects/784430514655/secrets/DATABASE_URL/versions/1
      env: 'DATABASE_URL'
    - versionName: projects/784430514655/secrets/JWT_TOKEN/versions/1
      env: 'JWT_TOKEN'
    - versionName: projects/784430514655/secrets/NODE_ENV/versions/1
      env: 'NODE_ENV'
    - versionName: projects/784430514655/secrets/SECRET_KEY_ONE/versions/1
      env: 'SECRET_KEY_ONE'
    - versionName: projects/784430514655/secrets/SECRET_KEY_TWO/versions/1
      env: 'SECRET_KEY_TWO'
    - versionName: projects/784430514655/secrets/CLIENT_URL/versions/1
      env: 'CLIENT_URL'
    - versionName: projects/784430514655/secrets/REDIS_HOST/versions/1
      env: 'REDIS_HOST'
    - versionName: projects/784430514655/secrets/CLOUD_NAME/versions/1
      env: 'CLOUD_NAME'
    - versionName: projects/784430514655/secrets/CLOUD_API_KEY/versions/1
      env: 'CLOUD_API_KEY'
    - versionName: projects/784430514655/secrets/CLOUD_API_SECRET/versions/1
      env: 'CLOUD_API_SECRET'
    - versionName: projects/784430514655/secrets/SENDER_EMAIL/versions/1
      env: 'SENDER_EMAIL'
    - versionName: projects/784430514655/secrets/SENDER_EMAIL_PASSWORD/versions/1
      env: 'SENDER_EMAIL_PASSWORD'
    - versionName: projects/784430514655/secrets/SENDGRID_API_KEY/versions/1
      env: 'SENDGRID_API_KEY'
    - versionName: projects/784430514655/secrets/SENDGRID_SENDER/versions/1
      env: 'SENDGRID_SENDER'
