apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-server
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/server-main-422100/imagesregistry/main-server:latest
        name: main-server
        resources: {}
status: {}
