apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-api-server
  name: client-api-server
spec:
  ports:
  - name: "4000"
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: client-api-server
  type: NodePort
status:
  loadBalancer: {}
