@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/images/profile
Content-Type: application/json
Accept: application/json
withCredentials: true



###
DELETE {{baseUrl}}/{{urlPath}}/images/65557b2d7cbbe4a799371f8e
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/images/background/d7nwebra4oge5k70rfki
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/images/65557b2d7cbbe4a799371f8e
Content-Type: application/json
Accept: application/json
withCredentials: true
