@baseUrl = http://localhost:5000
@urlPath = api/v1



###
POST {{baseUrl}}/{{urlPath}}/send
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "receiverId": "655d4598e9c556061ea33838"
}
###
POST {{baseUrl}}/{{urlPath}}/accept/6560f66f97201779c2c7411a
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/reject/
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "ID_DEL_USUARIO_QUE_ENVIA",
  "receiverId": "ID_DEL_USUARIO_QUE_RECIBE"
}

###
GET  {{baseUrl}}/{{urlPath}}/friend-requests/
Content-Type: application/json
Accept: application/json
withCredentials: true



#  this.router.post('/send', authMiddleware.checkAuthentication, this.friendRequestController.sendFriendRequest);
#     this.router.post('/accept/:requestId', authMiddleware.checkAuthentication, this.friendRequestController.acceptFriendRequest);
#     this.router.post('/reject/:requestId', authMiddleware.checkAuthentication, this.friendRequestController.rejectFriendRequest);


#     this.router.get('/friend-requests', authMiddleware.checkAuthentication, this.friendRequestController.getFriendRequests);
#     this.router.delete('/friend-requests/:requestId', authMiddleware.checkAuthentication, this.friendRequestController.cancelFriendRequest);
